[project]
name = "mnemolib"
version = "0.1.0"
authors = [
    { name = "Laura Sirumapea", email = "lauraawise07@gmail.com" },
    { name = "Desnita Pardosi", email = "desnitapardosi@gmail.com" },
    { name = "Mia Sibuea", email = "miasibuea152@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[project.scripts]
mnemolib = "mnemolib:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
